server {
    listen 9005;
    server_name _;

    root /usr/share/nginx/html;

    location /admin-console/ {
        try_files $uri $uri/ /admin-console/index.html;
    }

    # cache built assets aggressively
    location /admin-console/assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}